// Mocks generated by Mockito 5.4.4 from annotations
// in aura_mobile/test/domain/services/document_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura_mobile/ai/run_anywhere_service.dart' as _i2;
import 'package:aura_mobile/domain/entities/document.dart' as _i5;
import 'package:aura_mobile/domain/repositories/document_repository.dart'
    as _i4;
import 'package:aura_mobile/domain/services/vector_store_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RunAnywhere].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAnywhere extends _i1.Mock implements _i2.RunAnywhere {
  MockRunAnywhere() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isModelLoaded => (super.noSuchMethod(
        Invocation.getter(#isModelLoaded),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<_i2.DownloadUpdate> get downloadUpdates => (super.noSuchMethod(
        Invocation.getter(#downloadUpdates),
        returnValue: _i3.Stream<_i2.DownloadUpdate>.empty(),
      ) as _i3.Stream<_i2.DownloadUpdate>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> downloadModel(
    String? url,
    String? destinationPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadModel,
          [
            url,
            destinationPath,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cancelDownload(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [taskId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getTaskIdForUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getTaskIdForUrl,
          [url],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> loadModel(String? modelPath) => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [modelPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<String> chat({
    required String? prompt,
    String? systemPrompt,
    int? maxTokens = 512,
    Duration? timeout,
    double? temperature = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [],
          {
            #prompt: prompt,
            #systemPrompt: systemPrompt,
            #maxTokens: maxTokens,
            #timeout: timeout,
            #temperature: temperature,
          },
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<List<double>> getEmbeddings(String? text) => (super.noSuchMethod(
        Invocation.method(
          #getEmbeddings,
          [text],
        ),
        returnValue: _i3.Future<List<double>>.value(<double>[]),
      ) as _i3.Future<List<double>>);

  @override
  void unloadModel() => super.noSuchMethod(
        Invocation.method(
          #unloadModel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i4.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveDocument(_i5.Document? document) => (super.noSuchMethod(
        Invocation.method(
          #saveDocument,
          [document],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Document>> getAllDocuments() => (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Document>>.value(<_i5.Document>[]),
      ) as _i3.Future<List<_i5.Document>>);

  @override
  _i3.Future<void> saveChunks(List<_i5.DocumentChunk>? chunks) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunks,
          [chunks],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.DocumentChunk>> getAllChunks() => (super.noSuchMethod(
        Invocation.method(
          #getAllChunks,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.DocumentChunk>>.value(<_i5.DocumentChunk>[]),
      ) as _i3.Future<List<_i5.DocumentChunk>>);

  @override
  _i3.Future<void> deleteDocument(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [VectorStoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVectorStoreService extends _i1.Mock
    implements _i6.VectorStoreService {
  MockVectorStoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double cosineSimilarity(
    List<double>? vectorA,
    List<double>? vectorB,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cosineSimilarity,
          [
            vectorA,
            vectorB,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}
