// Mocks generated by Mockito 5.4.4 from annotations
// in aura_mobile/test/presentation/providers/model_selector_retry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura_mobile/ai/run_anywhere_service.dart' as _i6;
import 'package:aura_mobile/data/datasources/llm_service.dart' as _i7;
import 'package:aura_mobile/data/datasources/model_manager.dart' as _i2;
import 'package:aura_mobile/domain/entities/model_info.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ModelManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelManager extends _i1.Mock implements _i2.ModelManager {
  MockModelManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> getDownloadedModels() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadedModels,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isModelDownloaded(String? modelId) => (super.noSuchMethod(
        Invocation.method(
          #isModelDownloaded,
          [modelId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> verifyAndCleanupModel(String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyAndCleanupModel,
          [modelId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getAvailableDiskSpace() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableDiskSpace,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> validateDiskSpace(String? modelId) => (super.noSuchMethod(
        Invocation.method(
          #validateDiskSpace,
          [modelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getModelPath(String? modelId) => (super.noSuchMethod(
        Invocation.method(
          #getModelPath,
          [modelId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getModelPath,
            [modelId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> deleteModel(String? modelId) => (super.noSuchMethod(
        Invocation.method(
          #deleteModel,
          [modelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getModelSize(String? modelId) => (super.noSuchMethod(
        Invocation.method(
          #getModelSize,
          [modelId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalStorageUsed() => (super.noSuchMethod(
        Invocation.method(
          #getTotalStorageUsed,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i5.ModelInfo? getModelById(String? modelId) =>
      (super.noSuchMethod(Invocation.method(
        #getModelById,
        [modelId],
      )) as _i5.ModelInfo?);
}

/// A class which mocks [RunAnywhere].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAnywhere extends _i1.Mock implements _i6.RunAnywhere {
  MockRunAnywhere() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isModelLoaded => (super.noSuchMethod(
        Invocation.getter(#isModelLoaded),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<_i6.DownloadUpdate> get downloadUpdates => (super.noSuchMethod(
        Invocation.getter(#downloadUpdates),
        returnValue: _i3.Stream<_i6.DownloadUpdate>.empty(),
      ) as _i3.Stream<_i6.DownloadUpdate>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> downloadModel(
    String? url,
    String? destinationPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadModel,
          [
            url,
            destinationPath,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cancelDownload(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [taskId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getTaskIdForUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getTaskIdForUrl,
          [url],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> loadModel(String? modelPath) => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [modelPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<String> chat({
    required String? prompt,
    String? systemPrompt,
    int? maxTokens = 512,
    Duration? timeout,
    double? temperature = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [],
          {
            #prompt: prompt,
            #systemPrompt: systemPrompt,
            #maxTokens: maxTokens,
            #timeout: timeout,
            #temperature: temperature,
          },
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<List<double>> getEmbeddings(String? text) => (super.noSuchMethod(
        Invocation.method(
          #getEmbeddings,
          [text],
        ),
        returnValue: _i3.Future<List<double>>.value(<double>[]),
      ) as _i3.Future<List<double>>);

  @override
  void unloadModel() => super.noSuchMethod(
        Invocation.method(
          #unloadModel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LLMServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMServiceImpl extends _i1.Mock implements _i7.LLMServiceImpl {
  MockLLMServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isModelLoaded => (super.noSuchMethod(
        Invocation.getter(#isModelLoaded),
        returnValue: false,
      ) as bool);

  @override
  _i7.ModelTier get modelTier => (super.noSuchMethod(
        Invocation.getter(#modelTier),
        returnValue: _i7.ModelTier.large,
      ) as _i7.ModelTier);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadModel(String? modelPath) => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [modelPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<String> chat(
    String? prompt, {
    String? systemPrompt,
    int? maxTokens = 512,
    double? temperature = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [prompt],
          {
            #systemPrompt: systemPrompt,
            #maxTokens: maxTokens,
            #temperature: temperature,
          },
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
}
