// Mocks generated by Mockito 5.4.4 from annotations
// in aura_mobile/test/workflow_splitter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura_mobile/data/datasources/llm_service.dart' as _i4;
import 'package:aura_mobile/domain/services/intent_detection_service.dart'
    as _i5;
import 'package:aura_mobile/domain/services/llm_intent_classifier.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LLMIntentClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMIntentClassifier extends _i1.Mock
    implements _i2.LLMIntentClassifier {
  @override
  _i3.Future<_i2.ClassifiedIntent?> classify(String? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #classify,
          [message],
        ),
        returnValue: _i3.Future<_i2.ClassifiedIntent?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.ClassifiedIntent?>.value(),
      ) as _i3.Future<_i2.ClassifiedIntent?>);
}

/// A class which mocks [LLMService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMService extends _i1.Mock implements _i4.LLMService {
  @override
  bool get isModelLoaded => (super.noSuchMethod(
        Invocation.getter(#isModelLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadModel(String? modelPath) => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [modelPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.ModelTier get modelTier => (super.noSuchMethod(
        Invocation.getter(#modelTier),
        returnValue: _i4.ModelTier.large,
        returnValueForMissingStub: _i4.ModelTier.large,
      ) as _i4.ModelTier);

  @override
  _i3.Stream<String> chat(
    String? prompt, {
    String? systemPrompt,
    int? maxTokens,
    double? temperature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [prompt],
          {
            #systemPrompt: systemPrompt,
            #maxTokens: maxTokens,
            #temperature: temperature,
          },
        ),
        returnValue: _i3.Stream<String>.empty(),
        returnValueForMissingStub: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
}

/// A class which mocks [IntentDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntentDetectionService extends _i1.Mock
    implements _i5.IntentDetectionService {
  @override
  _i3.Future<_i5.IntentType> detectIntent(
    String? message, {
    List<Map<String, String>>? history,
    bool? hasDocuments = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectIntent,
          [message],
          {
            #history: history,
            #hasDocuments: hasDocuments,
          },
        ),
        returnValue:
            _i3.Future<_i5.IntentType>.value(_i5.IntentType.normalChat),
        returnValueForMissingStub:
            _i3.Future<_i5.IntentType>.value(_i5.IntentType.normalChat),
      ) as _i3.Future<_i5.IntentType>);

  @override
  bool containsURL(String? text) => (super.noSuchMethod(
        Invocation.method(
          #containsURL,
          [text],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String? extractEmailAddress(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractEmailAddress,
          [message],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  String extractEmailTopic(
    String? message,
    String? emailAddress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractEmailTopic,
          [
            message,
            emailAddress,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractEmailTopic,
            [
              message,
              emailAddress,
            ],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractEmailTopic,
            [
              message,
              emailAddress,
            ],
          ),
        ),
      ) as String);

  @override
  String extractSearchQuery(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractSearchQuery,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractSearchQuery,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractSearchQuery,
            [message],
          ),
        ),
      ) as String);

  @override
  String extractUrl(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractUrl,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractUrl,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractUrl,
            [message],
          ),
        ),
      ) as String);

  @override
  String extractMemoryContent(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractMemoryContent,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractMemoryContent,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractMemoryContent,
            [message],
          ),
        ),
      ) as String);

  @override
  String extractAppName(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractAppName,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractAppName,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractAppName,
            [message],
          ),
        ),
      ) as String);

  @override
  String extractSettingsType(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractSettingsType,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractSettingsType,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractSettingsType,
            [message],
          ),
        ),
      ) as String);

  @override
  String extractContactName(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractContactName,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractContactName,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractContactName,
            [message],
          ),
        ),
      ) as String);

  @override
  Map<String, String> extractSMSDetails(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractSMSDetails,
          [message],
        ),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String extractNavigationDestination(String? message) => (super.noSuchMethod(
        Invocation.method(
          #extractNavigationDestination,
          [message],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractNavigationDestination,
            [message],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #extractNavigationDestination,
            [message],
          ),
        ),
      ) as String);
}
