// Mocks generated by Mockito 5.4.4 from annotations
// in aura_mobile/test/workflow_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura_mobile/data/datasources/llm_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LLMService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMService extends _i1.Mock implements _i2.LLMService {
  @override
  bool get isModelLoaded => (super.noSuchMethod(
        Invocation.getter(#isModelLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadModel(String? modelPath) => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [modelPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i2.ModelTier get modelTier => (super.noSuchMethod(
        Invocation.getter(#modelTier),
        returnValue: _i2.ModelTier.large,
        returnValueForMissingStub: _i2.ModelTier.large,
      ) as _i2.ModelTier);

  @override
  _i3.Stream<String> chat(
    String? prompt, {
    String? systemPrompt,
    int? maxTokens,
    double? temperature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [prompt],
          {
            #systemPrompt: systemPrompt,
            #maxTokens: maxTokens,
            #temperature: temperature,
          },
        ),
        returnValue: _i3.Stream<String>.empty(),
        returnValueForMissingStub: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
}
